---
title: "COMPSCIX 415.2 Homework 1"
output: html_document
author: "Michelle Gomez"
date: 'June 12 2018'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
My Github repository for my assignments can be found at this URL:[(https://github.com/michelle-gomez/compscix-415-2-assignments)] (https://github.com/michelle-gomez/compscix-415-2-assignments)
```{r load_packages, echo=FALSE, message=FALSE, warning=FALSE}
library(mdsr)
library(tidyverse)
```
###Question 1:
```{r}
glimpse(WorldCities)
```
There are 23018 observations and 10 variables.
The variables include name, date, latitude, longitude, county, population, region, etc.  

### Question 2:
```{r}
data("WorldCities")
WorldCities <- head(WorldCities, 200) # 200 rows
country_col <- WorldCities$country
region_col<-WorldCities$region
unique(region_col)
```
### Question 3:
```{r}
WorldCities %>% select(country) %>% unique()
```
###Question 4:
```{r}
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
xlab('Pop') +
ylab ('Concentration in city') +
ggtitle('Population in Cities') +
theme_bw()
```

